### ISSUE TITLE
[Bug]: Wrong Factory class name in Service layer

### ISSUE THREAD

**Issue by Lkopo** [nexusunited/spryker-kit-intellij-plugin#24]
### Contact Details

eduard@karpiel.sk

### What happened?

When generating Factory class via SprykerKit for module in Service layer the plugin suggests class name as `ModuleNameFactory`. However the correct factory class name for service module should be <pre>ModuleName**Service**Factory</pre>

As this part is missing, Spryker is unable to find service Factory class which leads to the application failure.

### Version

1.0.5

**Comment by patrickjaja** [comment]
Thank you for reporting. Its fixed in 1.0.7 (will be available in next hours).

**Comment by Lkopo** [comment]
Glad to help, thank you for fix!
